const preamble = [
  "You are implementing one issue of a larger spec on the `helix` branch of the marimo fork at /home/valter/repos/marimo (cwd).",
  "Read first, in this order: the issue file named below, /home/valter/repos/marimo/.scratch/helix-preset/spec.md, /home/valter/repos/marimo/.scratch/helix-preset/codemirror-helix-notes.md (engine facts gathered from the published package), and /home/valter/repos/marimo/AGENTS.md.",
  "Issue cross-references: #PREFACTOR = issue 01, #PRESET = 02, #NAV = 03, #REARR = 04, #MULTI = 05, #AI = 06, #REMAP = 07. Earlier issues in that order are already committed on the branch when yours starts; read `git log` and the relevant diffs to build on them instead of redoing them.",
  "Environment: before any shell command run `export PATH=$HOME/.local/bin:$PATH COREPACK_HOME=$HOME/.cache/corepack COREPACK_ENABLE_DOWNLOAD_PROMPT=0`. pnpm 10.28.2, make, pixi and uv are then on PATH. frontend/node_modules and the repo .venv are already installed. Both `make fe-check` and `make py-check` pass on the starting commit.",
  "Frontend tests: `cd frontend && pnpm vitest run <path>`. Python tests: `uv run --group test pytest <path>`.",
  "Scope: implement exactly this issue and its acceptance criteria. Do not implement later issues. Do not edit files under .scratch/ except as the issue asks you to record results (record them in the issue's own file under a `## Result` heading).",
  "Quality bar: this is an open source React/TypeScript + Python code base. Write idiomatic, typed, tested code; keep comments to the why; docstrings use single backticks; follow existing patterns in the files you touch.",
  "Finish: run `make check` (it autofixes lint/format and runs typecheck) and the relevant test files; all must pass. Then `git add` your changes and commit on the current branch with a conventional-commit message (feat/refactor/fix(helix): ...). Never open a pull request, never push. If `make check` leaves unrelated modifications you did not intend, inspect and revert them rather than committing them.",
  "Report back (concise): files changed, commit hash, test and check results verbatim summary, anything left undone and why, and any decision you made that the spec left open.",
].join("\n");

const smoke = "Headless smoke check instructions: build the frontend once with `make fe` (several minutes; it writes marimo/_static). Create a temp directory containing a `.marimo.toml` with `[keymap]\\npreset = \"helix\"` plus a small notebook, and start `uv run marimo edit --headless --no-token --port 2718 <notebook>` from that directory (the repo .venv has marimo installed editable). Drive it with Playwright from frontend/node_modules (`import { chromium } from 'playwright'`, `chromium.launch({ executablePath: process.env.HOME + '/.nix-profile/bin/chromium', headless: true })`). Put the script under /tmp, not in the repo. Kill the server when done.";

const issues = [
  { key: "issue01-prefactor", label: "Prefactor command-mode key tables", file: "01-prefactor-command-mode-tables.md", model: "claude-bridge/claude-sonnet-5:medium", extra: "This is a pure refactor: behaviour must be identical for the default and vim presets, and the existing vim navigation tests must pass unchanged. Keep the new function small and well-typed so the Helix table can be added as a sibling entry later." },
  { key: "issue02-preset", label: "Add helix keymap preset with engine", file: "02-helix-preset.md", model: "claude-bridge/claude-fable-5-1:high", extra: "Add the dependency with `cd frontend && pnpm add codemirror-helix@0.6.0` (check the lockfile diff is limited to that package). Include the `:` commands `w`, `q`, `wq` from the spec. Isolate normal-mode detection in one helper as the notes describe. Also implement the no-boundary-jump behaviour and keep marimo's modifier hotkeys working. " + smoke + " Record the smoke check result in the issue file." },
  { key: "issue03-nav", label: "Helix cell-mode navigation table", file: "03-cell-mode-navigation.md", model: "claude-bridge/claude-opus-5-5:high", extra: "Add the Helix table as a sibling to the vim table in the preset-keyed function from issue 01. For `i`, use the public `runScopeHandlers` approach from the notes (or an equivalent you verify) so the editor opens in insert mode; add a focused unit test for that seam." },
  { key: "issue04-rearr", label: "Helix cell-mode rearranging keys", file: "04-cell-mode-rearranging.md", model: "claude-bridge/claude-sonnet-5:medium", extra: "Extend the Helix table from issue 03. Reuse the existing clipboard copy/paste helpers, the existing delete action with its running-cell guard, and the existing undo-delete action. Single-press `d`, no pending-delete confirmation." },
  { key: "issue05-multi", label: "Helix cell-mode select mode", file: "05-cell-mode-multi-select.md", model: "claude-bridge/claude-opus-5-5:high", extra: "Introduce the per-notebook select-mode state in the existing selection state module, expose a `data-select-mode` attribute on the cell wrapper next to `data-selected`, and add a distinct ring colour in the default stylesheet. Make `shift+j`/`shift+k` no-ops when more than one cell is selected." },
  { key: "issue06-ai-button", label: "Keep AI edit button quiet in normal mode", file: "06-ai-edit-button.md", model: "claude-bridge/claude-fable-5-1:high", extra: "Reproduce first using the headless-browser smoke setup and record the outcome in the issue file under `## Result`. " + smoke + " Only if it reproduces, suppress the trigger while the engine is in normal mode using the normal-mode helper from issue 02, leaving default and vim behaviour unchanged with existing tests passing. If it does not reproduce, record why with evidence and make no code change beyond what is needed." },
  { key: "issue07-remaps", label: "Personal helix remaps commit", file: "07-personal-remaps.md", model: "claude-bridge/claude-opus-5-5:high", extra: "Layer the four remaps as a higher-precedence keymap (see the notes on precedence) applied only in the helix preset bundle. The commit message must say it is personal configuration, not for upstream. No unit tests. Verify by hand in the headless setup and record the result in the issue file. " + smoke },
];

const results = [];
for (const issue of issues) {
  const task = preamble + "\n\nIssue file: /home/valter/repos/marimo/.scratch/helix-preset/issues/" + issue.file + "\n\nIssue-specific guidance: " + issue.extra;
  const r = await runs.run(issue.key, { label: issue.label, agent: "worker", model: issue.model, task, timeoutMs: 9000000 });
  results.push({ key: issue.key, output: r.output });
  emit("done", issue.key);
}
return results;
